60 Realisation/Source Code/CNPMNC/CNPMNC/Areas/Admin/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CNPMNC.Areas.Admin.Controllers
{
    public class HomeController : BaseController
    {
        // GET: Admin/Home
        public ActionResult Index()
        {
            return View();
        }
    }
}

60 Realisation/Source Code/CNPMNC/CNPMNC/Controllers/CT_DT_ThangController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CNPMNC.Areas.Admin.Controllers;
using CNPMNC.Models;

namespace CNPMNC.Controllers
{
    public class CT_DT_ThangController : BaseController
    {
        private CSDLContext db = new CSDLContext();

        // GET: CT_DT_Thang
        public ActionResult Index()
        {
            var cT_DT_Thangs = db.CT_DT_Thangs.Include(c => c.Doanh_Thu_Thang).Include(c => c.Phong);
            return View(cT_DT_Thangs.ToList());
        }

        // GET: CT_DT_Thang/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CT_DT_Thang cT_DT_Thang = db.CT_DT_Thangs.Find(id);
            if (cT_DT_Thang == null)
            {
                return HttpNotFound();
            }
            return View(cT_DT_Thang);
        }

        // GET: CT_DT_Thang/Create
        public ActionResult Create()
        {
            ViewBag.ThangID = new SelectList(db.Doanh_Thu_Thangs, "ThangID", "Thang");
            ViewBag.PhongID = new SelectList(db.Phongs, "PhongID", "TenPhong");
            return View();
        }

        // POST: CT_DT_Thang/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CT_DTT_ID,DoanhThu,TyLe,ThangID,PhongID")] CT_DT_Thang cT_DT_Thang)
        {
            if (ModelState.IsValid)
            {
                db.CT_DT_Thangs.Add(cT_DT_Thang);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ThangID = new SelectList(db.Doanh_Thu_Thangs, "ThangID", "Thang", cT_DT_Thang.ThangID);
            ViewBag.PhongID = new SelectList(db.Phongs, "PhongID", "TenPhong", cT_DT_Thang.PhongID);
            return View(cT_DT_Thang);
        }

        // GET: CT_DT_Thang/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CT_DT_Thang cT_DT_Thang = db.CT_DT_Thangs.Find(id);
            if (cT_DT_Thang == null)
            {
                return HttpNotFound();
            }
            ViewBag.ThangID = new SelectList(db.Doanh_Thu_Thangs, "ThangID", "Thang", cT_DT_Thang.ThangID);
            ViewBag.PhongID = new SelectList(db.Phongs, "PhongID", "TenPhong", cT_DT_Thang.PhongID);
            return View(cT_DT_Thang);
        }

        // POST: CT_DT_Thang/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "CT_DTT_ID,DoanhThu,TyLe,ThangID,PhongID")] CT_DT_Thang cT_DT_Thang)
        {
            if (ModelState.IsValid)
            {
                db.Entry(cT_DT_Thang).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ThangID = new SelectList(db.Doanh_Thu_Thangs, "ThangID", "Thang", cT_DT_Thang.ThangID);
            ViewBag.PhongID = new SelectList(db.Phongs, "PhongID", "TenPhong", cT_DT_Thang.PhongID);
            return View(cT_DT_Thang);
        }

        // GET: CT_DT_Thang/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CT_DT_Thang cT_DT_Thang = db.CT_DT_Thangs.Find(id);
            if (cT_DT_Thang == null)
            {
                return HttpNotFound();
            }
            return View(cT_DT_Thang);
        }

        // POST: CT_DT_Thang/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            CT_DT_Thang cT_DT_Thang = db.CT_DT_Thangs.Find(id);
            db.CT_DT_Thangs.Remove(cT_DT_Thang);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

60 Realisation/Source Code/CNPMNC/CNPMNC/Controllers/CT_Hoa_DonController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CNPMNC.Areas.Admin.Controllers;
using CNPMNC.Models;

namespace CNPMNC.Controllers
{
    public class CT_Hoa_DonController : BaseController
    {
        private CSDLContext db = new CSDLContext();

        // GET: CT_Hoa_Don
        public ActionResult Index()
        {
            var cT_Hoa_Dons = db.CT_Hoa_Dons.Include(c => c.Hoa_Don).Include(c => c.Phong);
            return View(cT_Hoa_Dons.ToList());
        }

        // GET: CT_Hoa_Don/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CT_Hoa_Don cT_Hoa_Don = db.CT_Hoa_Dons.Find(id);
            if (cT_Hoa_Don == null)
            {
                return HttpNotFound();
            }
            return View(cT_Hoa_Don);
        }

        // GET: CT_Hoa_Don/Create
        public ActionResult Create()
        {
            ViewBag.HoaDonID = new SelectList(db.Hoa_Dons, "HoaDonID", "HoaDonID");
            ViewBag.PhongID = new SelectList(db.Phongs, "PhongID", "TenPhong");
            return View();
        }

        // POST: CT_Hoa_Don/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CTHD_ID,SoNgayThue,ThanhTien,HoaDonID,PhongID")] CT_Hoa_Don cT_Hoa_Don)
        {
            if (ModelState.IsValid)
            {
                db.CT_Hoa_Dons.Add(cT_Hoa_Don);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.HoaDonID = new SelectList(db.Hoa_Dons, "HoaDonID", "HoaDonID", cT_Hoa_Don.HoaDonID);
            ViewBag.PhongID = new SelectList(db.Phongs, "PhongID", "TenPhong", cT_Hoa_Don.PhongID);
            return View(cT_Hoa_Don);
        }

        // GET: CT_Hoa_Don/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CT_Hoa_Don cT_Hoa_Don = db.CT_Hoa_Dons.Find(id);
            if (cT_Hoa_Don == null)
            {
                return HttpNotFound();
            }
            ViewBag.HoaDonID = new SelectList(db.Hoa_Dons, "HoaDonID", "HoaDonID", cT_Hoa_Don.HoaDonID);
            ViewBag.PhongID = new SelectList(db.Phongs, "PhongID", "TenPhong", cT_Hoa_Don.PhongID);
            return View(cT_Hoa_Don);
        }

        // POST: CT_Hoa_Don/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "CTHD_ID,SoNgayThue,ThanhTien,HoaDonID,PhongID")] CT_Hoa_Don cT_Hoa_Don)
        {
            if (ModelState.IsValid)
            {
                db.Entry(cT_Hoa_Don).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.HoaDonID = new SelectList(db.Hoa_Dons, "HoaDonID", "HoaDonID", cT_Hoa_Don.HoaDonID);
            ViewBag.PhongID = new SelectList(db.Phongs, "PhongID", "TenPhong", cT_Hoa_Don.PhongID);
            return View(cT_Hoa_Don);
        }

        // GET: CT_Hoa_Don/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CT_Hoa_Don cT_Hoa_Don = db.CT_Hoa_Dons.Find(id);
            if (cT_Hoa_Don == null)
            {
                return HttpNotFound();
            }
            return View(cT_Hoa_Don);
        }

        // POST: CT_Hoa_Don/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            CT_Hoa_Don cT_Hoa_Don = db.CT_Hoa_Dons.Find(id);
            db.CT_Hoa_Dons.Remove(cT_Hoa_Don);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

60 Realisation/Source Code/CNPMNC/CNPMNC/Controllers/HomeController.cs
using CNPMNC.Areas.Admin.Controllers;
using CNPMNC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CNPMNC.Controllers
{
    public class HomeController : Controller
    {
        CSDLContext db = new CSDLContext();
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Rules()
        {
            return View();
        }


        
    }
}

60 Realisation/Source Code/CNPMNC/CNPMNC/Areas/Admin/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Trang chủ";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<!-- Begin Page Content -->
<div class="container-fluid">

    <!-- Page Heading -->
    @*<div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Dashboard</h1>
    </div>*@

    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h4 class="m-0 font-weight-bold " style="text-align: center;">Quản lý khách sạn</h4>
        </div>
        <div class="card-body">
            <div class="wrapper">
                <div class="cards">
                    <div class="container-fluid">
                        <div class="row justify-content-center">
                            <div class="col-lg-3">
                                <figure class="card">
                                    <a class="collapse-item" href="@Url.Action("ListPhong", "ThuePhong_VM", new { area = ""})">
                                        <img src="~/Content/Admin/img/cardimg.jpg" />
                                        <figcaption>Lập danh mục phòng</figcaption>
                                    </a>
                                </figure>
                            </div>
                            <div class="col-lg-3">
                                <figure class="card">
                                    <a class="collapse-item" href="@Url.Action("Create", "ThuePhong_VM", new { area = ""})">
                                        <img src="~/Content/Admin/img/cardimg2.jpg" />
                                        <figcaption>Lập phiếu thuê phòng</figcaption>
                                    </a>
                                </figure>
                            </div>
                            <div class="col-lg-3">
                                <figure class="card">
                                    <a class="collapse-item" href="@Url.Action("ListPhong", "ThuePhong_VM", new { area = ""})">
                                        <img src="~/Content/Admin/img/cardimg3.jpg" />
                                        <figcaption>Tra cứu phòng</figcaption>
                                    </a>
                                </figure>
                            </div>
                            <div class="col-lg-3">
                                <figure class="card">
                                    <a class="collapse-item" href="@Url.Action("Index", "CT_Hoa_Don", new { area = ""})">
                                        <img src="~/Content/Admin/img/cardimg4.jpg" />
                                        <figcaption>Lập hoá đơn</figcaption>
                                    </a>
                                </figure>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-3">

                            </div>
                            <div class="col-lg-3">
                                <figure class="card">
                                    <a class="collapse-item" href="@Url.Action("Index", "CT_DT_Thang", new { area = ""})">
                                        <img src="~/Content/Admin/img/cardimg5.jpg" />
                                        <figcaption>Lập báo cáo tháng</figcaption>
                                    </a>
                                </figure>
                            </div>
                            <div class="col-lg-3">
                                <figure class="card">
                                    <a class="collapse-item" href="@Url.Action("Rules", "Home", new { area = ""})">
                                        <img src="~/Content/Admin/img/cardimg6.jpg" />
                                        <figcaption>Thay đổi quy định</figcaption>
                                    </a>
                                </figure>
                            </div>
                            <div class="col-lg-3">

                            </div>
                        </div>
                    </div>


                </div>
            </div>
        </div>
    </div>

    
</div>
<!-- /.container-fluid -->