60 Realisation/Source Code/CNPMNC/CNPMNC/Controllers/Doanh_Thu_ThangController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CNPMNC.Areas.Admin.Controllers;
using CNPMNC.Models;

namespace CNPMNC.Controllers
{
    public class Doanh_Thu_ThangController : BaseController
    {
        private CSDLContext db = new CSDLContext();

        // GET: Doanh_Thu_Thang
        public ActionResult Index()
        {
            return View(db.Doanh_Thu_Thangs.ToList());
        }

        // GET: Doanh_Thu_Thang/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Doanh_Thu_Thang doanh_Thu_Thang = db.Doanh_Thu_Thangs.Find(id);
            if (doanh_Thu_Thang == null)
            {
                return HttpNotFound();
            }
            return View(doanh_Thu_Thang);
        }

        // GET: Doanh_Thu_Thang/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Doanh_Thu_Thang/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ThangID,Thang")] Doanh_Thu_Thang doanh_Thu_Thang)
        {
            if (ModelState.IsValid)
            {
                db.Doanh_Thu_Thangs.Add(doanh_Thu_Thang);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(doanh_Thu_Thang);
        }

        // GET: Doanh_Thu_Thang/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Doanh_Thu_Thang doanh_Thu_Thang = db.Doanh_Thu_Thangs.Find(id);
            if (doanh_Thu_Thang == null)
            {
                return HttpNotFound();
            }
            return View(doanh_Thu_Thang);
        }

        // POST: Doanh_Thu_Thang/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ThangID,Thang")] Doanh_Thu_Thang doanh_Thu_Thang)
        {
            if (ModelState.IsValid)
            {
                db.Entry(doanh_Thu_Thang).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(doanh_Thu_Thang);
        }

        // GET: Doanh_Thu_Thang/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Doanh_Thu_Thang doanh_Thu_Thang = db.Doanh_Thu_Thangs.Find(id);
            if (doanh_Thu_Thang == null)
            {
                return HttpNotFound();
            }
            return View(doanh_Thu_Thang);
        }

        // POST: Doanh_Thu_Thang/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Doanh_Thu_Thang doanh_Thu_Thang = db.Doanh_Thu_Thangs.Find(id);
            db.Doanh_Thu_Thangs.Remove(doanh_Thu_Thang);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

60 Realisation/Source Code/CNPMNC/CNPMNC/Views/Doanh_Thu_Thang/Create.cshtml
@model CNPMNC.Models.Doanh_Thu_Thang

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
    <div class="container-fluid">
        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <h4 class="m-0 font-weight-bold text-primary">Thêm tháng</h4>
            </div>
            <div class="card-body">
                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()

                    <div class="form-horizontal">

                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <div class="form-group">
                            @Html.LabelFor(model => model.Thang, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Thang, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Thang, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="submit" value="Create" class="btn btn-primary" />
                            </div>
                        </div>
                    </div>
                }

                <div>
                    @Html.ActionLink("Back to List", "Index")
                </div>
            </div>
        </div>

        
    </div>

60 Realisation/Source Code/CNPMNC/CNPMNC/Views/Doanh_Thu_Thang/Delete.cshtml
@model CNPMNC.Models.Doanh_Thu_Thang

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
    <div class="container-fluid">
        <h3>Delete</h3>

        <h3>Are you sure you want to delete this?</h3>
        <div>
            <h4>Doanh_Thu_Thang</h4>
            <hr />
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.Thang)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Thang)
                </dd>

            </dl>

            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="form-actions no-color">
                    <input type="submit" value="Delete" class="btn btn-default" /> |
                    @Html.ActionLink("Back to List", "Index")
                </div>
            }
        </div>
    </div>

60 Realisation/Source Code/CNPMNC/CNPMNC/Views/Doanh_Thu_Thang/Details.cshtml
@model CNPMNC.Models.Doanh_Thu_Thang

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
    <div class="container-fluid">
        <h3>Details</h3>

        <div>
            <h4>Doanh_Thu_Thang</h4>
            <hr />
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.Thang)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Thang)
                </dd>

            </dl>
        </div>
        <p>
            @Html.ActionLink("Edit", "Edit", new { id = Model.ThangID }) |
            @Html.ActionLink("Back to List", "Index")
        </p>
    </div>

60 Realisation/Source Code/CNPMNC/CNPMNC/Views/Doanh_Thu_Thang/Edit.cshtml
@model CNPMNC.Models.Doanh_Thu_Thang

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
    <div class="container-fluid">
        <h3>Edit</h3>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <h4>Doanh_Thu_Thang</h4>
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.ThangID)

                <div class="form-group">
                    @Html.LabelFor(model => model.Thang, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Thang, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Thang, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Save" class="btn btn-default" />
                    </div>
                </div>
            </div>
        }

        <div>
            @Html.ActionLink("Back to List", "Index")
        </div>
    </div>

60 Realisation/Source Code/CNPMNC/CNPMNC/Views/Doanh_Thu_Thang/Index.cshtml
@model IEnumerable<CNPMNC.Models.Doanh_Thu_Thang>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
    <div class="container-fluid">
        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">Doanh thu tháng</h6>
            </div>
            <div class="card-body">
                <div class="row">
                    <div>
                        <a type="button" class="btn btn-primary" href="@Url.Action("Create", "Doanh_Thu_Thang", new { area = ""})" style="margin-bottom: 5px;">Thêm mới</a>
                    </div>
                    <div>
                        <a type="button" class="btn btn-primary" href="@Url.Action("Index", "CT_DT_THang", new { area = ""})" style="margin-bottom: 5px; margin-left: 5px;">Danh sách phòng</a>
                    </div>
                </div>
                <table class="table">
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.Thang)
                        </th>
                        <th></th>
                    </tr>

                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.Thang)
                            </td>
                            <td>
                                @Html.ActionLink("Edit", "Edit", new { id = item.ThangID }) |
                                @Html.ActionLink("Delete", "Delete", new { id = item.ThangID })
                            </td>
                        </tr>
                    }

                </table>
            </div>
        </div>

        
    </div>