60 Realisation/Source Code/CNPMNC/CNPMNC/ViewModels/ThuePhongVM.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CNPMNC.ViewModels
{
    public class ThuePhongVM
    {
        public int PhongID { get; set; }
        public DateTime NgayThue { get; set; }
        public string TenKhach { get; set; }
        public int LoaiKhachID { get; set; }
        public string CMND { get; set; }
        public string DiaChi { get; set; }
    }
}

60 Realisation/Source Code/CNPMNC/CNPMNC/Controllers/DM_PhongController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CNPMNC.Areas.Admin.Controllers;
using CNPMNC.Models;

namespace CNPMNC.Controllers
{
    public class DM_PhongController : BaseController
    {
        private CSDLContext db = new CSDLContext();

        // GET: DM_Phong
        public ActionResult Index()
        {
            return View(db.DM_Phongs.ToList());
        }

        // GET: DM_Phong/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DM_Phong dM_Phong = db.DM_Phongs.Find(id);
            if (dM_Phong == null)
            {
                return HttpNotFound();
            }
            return View(dM_Phong);
        }

        // GET: DM_Phong/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: DM_Phong/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "LoaiPhongID,TenLoaiPhong,DonGia")] DM_Phong dM_Phong)
        {
            if (ModelState.IsValid)
            {
                db.DM_Phongs.Add(dM_Phong);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(dM_Phong);
        }

        // GET: DM_Phong/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DM_Phong dM_Phong = db.DM_Phongs.Find(id);
            if (dM_Phong == null)
            {
                return HttpNotFound();
            }
            return View(dM_Phong);
        }

        // POST: DM_Phong/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "LoaiPhongID,TenLoaiPhong,DonGia")] DM_Phong dM_Phong)
        {
            if (ModelState.IsValid)
            {
                db.Entry(dM_Phong).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(dM_Phong);
        }

        // GET: DM_Phong/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DM_Phong dM_Phong = db.DM_Phongs.Find(id);
            if (dM_Phong == null)
            {
                return HttpNotFound();
            }
            return View(dM_Phong);
        }

        // POST: DM_Phong/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            DM_Phong dM_Phong = db.DM_Phongs.Find(id);
            db.DM_Phongs.Remove(dM_Phong);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

60 Realisation/Source Code/CNPMNC/CNPMNC/Controllers/PhongsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CNPMNC.Areas.Admin.Controllers;
using CNPMNC.Models;

namespace CNPMNC.Controllers
{
    public class PhongsController : BaseController
    {
        private CSDLContext db = new CSDLContext();

        // GET: Phongs
        public ActionResult Index()
        {
            var phongs = db.Phongs.Include(p => p.DM_Phong);
            return View(phongs.ToList());
        }

        // GET: Phongs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Phong phong = db.Phongs.Find(id);
            if (phong == null)
            {
                return HttpNotFound();
            }
            return View(phong);
        }

        // GET: Phongs/Create
        public ActionResult Create()
        {
            ViewBag.LoaiPhongID = new SelectList(db.DM_Phongs, "LoaiPhongID", "TenLoaiPhong");
            return View();
        }

        // POST: Phongs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "PhongID,TenPhong,GhiChu,TinhTrang,LoaiPhongID")] Phong phong)
        {
            if (ModelState.IsValid)
            {
                db.Phongs.Add(phong);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.LoaiPhongID = new SelectList(db.DM_Phongs, "LoaiPhongID", "TenLoaiPhong", phong.LoaiPhongID);
            return View(phong);
        }

        // GET: Phongs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Phong phong = db.Phongs.Find(id);
            if (phong == null)
            {
                return HttpNotFound();
            }
            ViewBag.LoaiPhongID = new SelectList(db.DM_Phongs, "LoaiPhongID", "TenLoaiPhong", phong.LoaiPhongID);
            return View(phong);
        }

        // POST: Phongs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "PhongID,TenPhong,GhiChu,TinhTrang,LoaiPhongID")] Phong phong)
        {
            if (ModelState.IsValid)
            {
                db.Entry(phong).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.LoaiPhongID = new SelectList(db.DM_Phongs, "LoaiPhongID", "TenLoaiPhong", phong.LoaiPhongID);
            return View(phong);
        }

        // GET: Phongs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Phong phong = db.Phongs.Find(id);
            if (phong == null)
            {
                return HttpNotFound();
            }
            return View(phong);
        }

        // POST: Phongs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Phong phong = db.Phongs.Find(id);
            db.Phongs.Remove(phong);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult TimPhong(string tenphong)
        {
            var phong = db.Phongs.Where(s => s.TenPhong.Contains(tenphong)).ToList();
            ViewBag.ds = phong;
            return View();
        }
    }
}

60 Realisation/Source Code/CNPMNC/CNPMNC/Controllers/ThuePhong_VMController.cs
using CNPMNC.Areas.Admin.Controllers;
using CNPMNC.Models;
using CNPMNC.ViewModels;
using System;
using System.Collections.Generic;
using System.Data.Entity.Validation;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;

namespace CNPMNC.Controllers
{
    public class ThuePhong_VMController : BaseController
    {
        CSDLContext db = new CSDLContext();
        // GET: ThuePhong_VM
        public ActionResult Index()
        {
            List<Phong> phong = db.Phongs.ToList();
            List<Thue_Phong> thuephong = db.Thue_Phongs.ToList();
            List<CT_Thue_Phong> ctThuephong = db.CT_Thue_Phongs.ToList();
            List<Khach_hang> khach = db.Khach_Hangs.ToList();
            List<CT_Khach_Hang> ctKhach = db.CT_Khach_Hangs.ToList();

            var dsThue = from p in phong
                         join t in thuephong on p.PhongID equals t.PhongID into table1
                         from t in table1.DefaultIfEmpty()
                         join ct in ctThuephong on t.TP_ID equals ct.TP_ID into table2
                         from ct in table2.DefaultIfEmpty()
                         join ck in ctKhach on ct.KhachID equals ck.KhachID into table3
                         from ck in table3.DefaultIfEmpty()
                         join k in khach on ck.LoaiKhachID equals k.LoaiKhachID into table4
                         from k in table4.DefaultIfEmpty()
                         select new ThuePhongList
                         {
                             phongdetails = p,
                             thuePhongdetails = t,
                             ctThuephongdetails = ct,
                             khachhangdetails = k,
                             ctKhachhangdetails = ck
                         };

            return View(dsThue);
        }
        //[HttpGet]
        public ActionResult Create()
        {
            ViewBag.LoaiKhachID = new SelectList(db.Khach_Hangs, "LoaiKhachID", "LoaiKhach");
            ViewBag.PhongID = new SelectList(db.Phongs, "PhongID", "TenPhong");

            return View();
        }

        [HttpPost]
        public ActionResult Create([Bind(Include = "PhongID,NgayThue,TenKhach,LoaiKhachID,CMND,DiaChi")] ThuePhongVM vm)
        {
            ViewBag.LoaiKhachID = new SelectList(db.Khach_Hangs, "LoaiKhachID", "LoaiKhach", vm.LoaiKhachID);
            ViewBag.PhongID = new SelectList(db.Phongs, "PhongID", "TenPhong", vm.PhongID);

            Phong phong = new Phong();
            Khach_hang khach = new Khach_hang();
            khach.LoaiKhach = khach.LoaiKhach;
            //phong.TenPhong = vm.TenPhong;

            //db.Phongs.Add(phong);
            //db.SaveChanges();

            Thue_Phong thue = new Thue_Phong();
            thue.NgayThue = vm.NgayThue;
            //thue.PhongID = phong.PhongID;
            db.Thue_Phongs.Add(thue);
            db.SaveChanges();

            CT_Khach_Hang kh = new CT_Khach_Hang();
            kh.TenKhach = vm.TenKhach;
            kh.CMND = vm.CMND;
            kh.DiaChi = vm.DiaChi;
            //kh.LoaiKhachID = khach.LoaiKhachID;
            db.CT_Khach_Hangs.Add(kh);
            db.SaveChanges();

            CT_Thue_Phong cttp = new CT_Thue_Phong();
            cttp.TP_ID = thue.TP_ID;
            cttp.KhachID = kh.KhachID;
            //cttp.Khach_Hang.LoaiKhachID = khach.LoaiKhachID;
            db.CT_Thue_Phongs.Add(cttp);
            db.SaveChanges();

            //try
            //{
            //    if (ModelState.IsValid)
            //    {
            //        Phong phong = new Phong();
            //        Thue_Phong thue = new Thue_Phong();
            //        CT_Khach_Hang kh = new CT_Khach_Hang();
            //        CT_Thue_Phong cttp = new CT_Thue_Phong();
            //        db.Phongs.Add(phong);
            //        db.Thue_Phongs.Add(thue);
            //        db.CT_Khach_Hangs.Add(kh);
            //        db.CT_Thue_Phongs.Add(cttp);
            //        db.SaveChanges();
            //        return RedirectToAction("ListPhong", "ThuePhong_VM");

            //    }

            //}
            //catch (DbEntityValidationException eve)
            //{
            //    foreach (var ve in eve.EntityValidationErrors)
            //    {
            //        Console.WriteLine("- Property: \"{0}\", Value: \"{1}\", Error: \"{2}\"",
            //    ve.PropertyName,
            //    eve.Entry.CurrentValues.GetValue<object>(ve.PropertyName),
            //    ve.ErrorMessage);
            //    }
            //    throw;
            //}



            SetAlert("Thêm phiếu thành công", "success");
            return RedirectToAction("ListPhong", "ThuePhong_VM");
        }

        public ActionResult ListPhong()
        {
            var listp = from a in db.DM_Phongs
                        join p in db.Phongs on a.LoaiPhongID equals p.LoaiPhongID
                        select new ListPhongVM()
                        {
                            TenPhong = p.TenPhong,
                            TenLoaiPhong = p.DM_Phong.TenLoaiPhong,
                            DonGia = p.DM_Phong.DonGia,
                            TinhTrang = p.TinhTrang,
                            GhiChu = p.GhiChu
                        };

            ViewData["listp"] = listp;
            //ViewBag.ds = listp;
            
            return View();
        }

        public ActionResult TimPhong(string tenphong)
        {
            var tenp = db.Phongs.Where(s => s.TenPhong.Contains(tenphong)).ToList();
            ViewData["tenp"] = tenp;
            return View();
        }
    }
}

60 Realisation/Source Code/CNPMNC/CNPMNC/Views/ThuePhong_VM/Create.cshtml
@model CNPMNC.ViewModels.ThuePhongVM

@{
    ViewBag.Title = "Lập phiếu thuê phòng";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
@*<div class="card shadow mb-4">
        <div class="card-header py-3">
            <h4 class="m-0 font-weight-bold text-primary">Thêm loại phòng</h4>
        </div>
        <div class="card-body">

        </div>
    </div>*@


<div class="container-fluid">
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Lập phiếu thuê phòng</h6>
        </div>
        <div class="card-body">
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="form-horizontal">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="row">
                        <div class="col-lg-6">
                            <div class="form-group">
                                @*@Html.LabelFor(model => model.PhongID, "PhongID", htmlAttributes: new { @class = "control-label col-md-2" })*@
                                <div class="control-label col-lg-12 col-md-12">
                                    <h6>Phòng</h6>
                                </div>
                                <div class="col-lg-12 col-md-12">
                                    @Html.DropDownList("PhongID", null, htmlAttributes: new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.PhongID, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="form-group">
                                @*@Html.LabelFor(model => model.NgayThue, htmlAttributes: new { @class = "control-label col-md-2" })*@
                                <div class="control-label col-lg-12 col-md-12">
                                    <h6>Ngày thuê</h6>
                                </div>
                                <div class="col-lg-12 col-md-12">
                                    @Html.EditorFor(model => model.NgayThue, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.NgayThue, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-lg-3">
                            <div class="form-group">
                                @*@Html.LabelFor(model => model.TenKhach, htmlAttributes: new { @class = "control-label col-md-2" })*@
                                <div class="control-label col-lg-12 col-md-12">
                                    <h6>Tên khách</h6>
                                </div>
                                <div class="col-lg-12 col-md-12">
                                    @Html.EditorFor(model => model.TenKhach, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.TenKhach, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-3">
                            <div class="form-group">
                                @*@Html.LabelFor(model => model.LoaiKhachID, "LoaiKhachID", htmlAttributes: new { @class = "control-label col-md-2" })*@
                                <div class="control-label col-lg-12 col-md-12">
                                    <h6>Loại khách</h6>
                                </div>
                                <div class="col-lg-12 col-md-12">
                                    @Html.DropDownList("LoaiKhachID", null, htmlAttributes: new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.LoaiKhachID, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-3">
                            <div class="form-group">
                                @*@Html.LabelFor(model => model.CMND, htmlAttributes: new { @class = "control-label col-md-2" })*@
                                <div class="control-label col-lg-12 col-md-12">
                                    <h6>CMND</h6>
                                </div>
                                <div class="col-lg-12 col-md-12">
                                    @Html.EditorFor(model => model.CMND, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.CMND, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-3">
                            <div class="form-group">
                                @*@Html.LabelFor(model => model.DiaChi, htmlAttributes: new { @class = "control-label col-md-2" })*@
                                <div class="control-label col-lg-12 col-md-12">
                                    <h6>Địa chỉ</h6>
                                </div>
                                <div class="col-lg-12 col-md-12">
                                    @Html.EditorFor(model => model.DiaChi, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.DiaChi, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Tạo mới" class="btn btn-primary" /> |
                            <a type="button" class="btn btn-primary" href="@Url.Action("ListPhong", "ThuePhong_VM", new { area = ""})">Quay về</a>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</div>

@section Scripts {

    @Scripts.Render("~/bundles/jqueryui")
    @Styles.Render("~/Content/cssjqryUi")

    <script type="text/javascript">

        $(document).ready(function () {
            $('input[type=datetime]').datepicker({
                dateFormat: "dd/M/yy",
                changeMonth: true,
                changeYear: true,
                yearRange: "-60:+0"
            });

        });
    </script>

}

60 Realisation/Source Code/CNPMNC/CNPMNC/Views/ThuePhong_VM/Index.cshtml
@model IEnumerable<CNPMNC.Models.ThuePhongList>
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

    <div class="container-fluid">
        <h3>Index</h3>


        <table class="table">
            <tr>
                <th>
                    Tên phòng
                </th>
                <th>
                    Ngày thuê
                </th>
                <th>
                    Tên khách hàng
                </th>
                <th>
                    Loại khách
                </th>
                <th>
                    CMND
                </th>
                <th>
                    Địa chỉ
                </th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @item.phongdetails.TenPhong
                    </td>
                    <td>
                        @item.thuePhongdetails.NgayThue
                    </td>
                    <td>
                        @item.ctKhachhangdetails.TenKhach
                    </td>
                    <td>
                        @item.khachhangdetails.LoaiKhach
                    <td>
                        @item.ctKhachhangdetails.CMND
                    </td>
                    <td>
                        @item.ctKhachhangdetails.DiaChi
                    </td>
                </tr>
            }

        </table>
    </div>

60 Realisation/Source Code/CNPMNC/CNPMNC/Views/ThuePhong_VM/ListPhong.cshtml
@{
    ViewBag.Title = "Danh sách phòng";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

    <div class="container-fluid">
        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">Danh sách phòng</h6>
            </div>
            <div class="card-body">
                <div class="row" style="margin-bottom: 10px; ">
                    @using (Html.BeginForm("TimPhong", "ThuePhong_VM", FormMethod.Post, new { @class = "form-inline d-flex justify-content-center md-form form-sm mt-0" }))
                    {
                        <i class="fas fa-search" aria-hidden="true"></i>
                        <input class="form-control form-control-sm ml-3 w-75" type="text" name="tenphong" placeholder="Tìm phòng.."
                               aria-label="Search">
                    }
                    <div>
                        <a type="button" class="btn btn-primary" href="@Url.Action("Create", "DM_Phong", new { area = ""})" style="margin-bottom: 5px;">Thêm loại phòng</a>
                    </div>
                    <div>
                        <a type="button" class="btn btn-primary" href="@Url.Action("Create", "Phongs", new { area = ""})" style="margin-bottom: 5px; margin-left: 10px;">Thêm phòng</a>
                    </div>
                </div>

                <table class="table">
                    <tr>
                        <th>
                            Tên phòng
                        </th>
                        <th>
                            Loại phòng
                        </th>
                        <th>
                            Đơn giá
                        </th>
                        <th>
                            Tình trạng
                        </th>
                        <th>Ghi chú</th>
                    </tr>

                    @foreach (var item in (dynamic)ViewData["listp"])
                    {
                        <tr>
                            <td>
                                @item.TenPhong
                            </td>
                            <td>
                                @item.TenLoaiPhong
                            </td>
                            <td>
                                @item.DonGia
                            </td>
                            <td>
                                @item.TinhTrang
                            </td>
                            <td>@item.GhiChu</td>
                        </tr>
                    }

                </table>
            </div>
            </div>
        </div>
        

60 Realisation/Source Code/CNPMNC/CNPMNC/Views/ThuePhong_VM/TimPhong.cshtml
@{
    ViewBag.Title = "Kết quả tìm kiếm";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

    <div class="container-fluid">
        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">Danh sách phòng</h6>
            </div>
            <div class="card-body">
                <div>
                    <a type="button" class="btn btn-primary" href="@Url.Action("TimPhong","ThuePhong_VM")" style="margin-bottom: 5px;">Quay về</a>
                </div>
                <table class="table">
                    <tr>
                        <th>
                            Tên phòng
                        </th>
                        <th>
                            Loại phòng
                        </th>
                        <th>
                            Đơn giá
                        </th>
                        <th>
                            Tình trạng
                        </th>
                    </tr>

                    @foreach (var item in (dynamic)ViewData["tenp"])
                    {
                        <tr>
                            <td>
                                @item.TenPhong
                            </td>
                            <td>
                                @item.DM_Phong.TenLoaiPhong
                            </td>
                            <td>
                                @item.DM_Phong.DonGia
                            </td>
                            <td>
                                @item.TinhTrang
                            </td>
                        </tr>
                    }

                </table>
            </div>
        </div>

        
    </div>